node { 
    withEnv(['registry=harsh1354/scripted',
			 'registryCredential=dockerHub']) {
		stage('Checkout') {
			git poll: false, url: 'https://github.com/harsh-crest/node-scripted.git' 
		}	

		stage('Build') {
			dockerImage=docker.build("${registry}:latest", "bulletin-board-app/")		
        }

		stage('Tag') {
			sh "docker tag ${registry}:latest ${registry}:${BUILD_NUMBER}"
        }
	}
}
