node { 
    withEnv(['registry = "harsh1354/scripted"',
             'registryCredential = 'dockerHub'']) {
		stage('checkout') {
			git poll: false, url: 'https://github.com/harsh-crest/node-scripted.git' 
		}

		stage('command') {
			echo "${registry}"
		}
	}
}
